# Generated by Django 4.2.23 on 2025-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienvenida', '0002_remove_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
